# Generated by Django 6.0.4 on 2026-07-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(db_index=True, editable=False, max_length=150, unique=True),
        ),
    ]
