# Generated by Django 6.0.4 on 2026-06-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountverificationotp',
            name='code',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='code',
            field=models.CharField(max_length=150),
        ),
    ]
