# Generated by Django 6.0.4 on 2026-07-04 05:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_unique_conversation_pair'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messaage',
            new_name='Message',
        ),
    ]
